stages:
  - test
  - docker

run_python_tests:
  stage: test
  image: python:3.12-slim
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    key:
      files:
        - requirements.txt
    paths:
      - .cache/pip
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
  script:
    - echo "Running unittests"
    - python -m unittest discover -s tests
  rules:
    - if: $CI_COMMIT_BRANCH

docker_build_and_run:
  stage: docker
  image: docker:24.0.7-cli
  services:
    - name: docker:24.0.7-dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    IMAGE_TAG: "hoewarmishetindelft-ci:$CI_COMMIT_SHORT_SHA"
  script:
    - echo "Building image from dockerfile..."
    - docker build -f Dockerfile -t "$IMAGE_TAG" .

    # Run the container targeting Delft, checking if it outputs the temperature.
    - echo "Running container for Delft..."
    - CONTAINER_ID=$(docker run -d -e PYTHONUNBUFFERED=1 "$IMAGE_TAG")
    - 'echo "Container ID: $CONTAINER_ID"'
    - EXIT_CODE=$(docker wait "$CONTAINER_ID")
    - docker logs "$CONTAINER_ID"
    - docker rm "$CONTAINER_ID" || true
    - '[ "$EXIT_CODE" -eq 0 ] || (echo "Delft container failed with exit code $EXIT_CODE" && exit "$EXIT_CODE")'

    # Run the container targeting Saratoga, checking if it outputs the temperature.
    - echo "Running container for Saratoga..."
    - CONTAINER_ID=$(docker run -d -e PYTHONUNBUFFERED=1 "$IMAGE_TAG" --saratoga)
    - 'echo "Container ID: $CONTAINER_ID"'
    - EXIT_CODE=$(docker wait "$CONTAINER_ID")
    - docker logs "$CONTAINER_ID"
    - docker rm "$CONTAINER_ID" || true
    - '[ "$EXIT_CODE" -eq 0 ] || (echo "Saratoga container failed with exit code $EXIT_CODE" && exit "$EXIT_CODE")'
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile